-- Ligue des Nations Concacaf 2026-2027 : phase de groupes des Ligues A, B et C uniquement,
-- sources Wikipedia (wikitext brut recoupe pour eviter les erreurs de resume) :
--   https://en.wikipedia.org/wiki/2026%E2%80%9327_CONCACAF_Nations_League
--   https://en.wikipedia.org/wiki/2026%E2%80%9327_CONCACAF_Nations_League_A
--   https://en.wikipedia.org/wiki/2026%E2%80%9327_CONCACAF_Nations_League_B
--   https://en.wikipedia.org/wiki/2026%E2%80%9327_CONCACAF_Nations_League_C
-- Ligue A (2 groupes de 6, mini-championnat a 4 journees, 23 sept-6 oct 2026) et Ligue C
-- (groupes de 3 en aller-retour, meme fenetre) entierement calendarisees. Ligue B (4 groupes
-- de 4, aller-retour, 24 sept-17 nov 2026) : les 4 premieres journees ont une date et une
-- heure precises ; les journees 5 et 6 (novembre 2026) n'ont, au moment de la redaction, qu'un
-- mois indicatif sans jour arrete dans le wikitext source ('{{Start date|2026|11||df=y}}') -
-- inserees avec date/heure NULL plutot que d'inventer une date. Quarts de finale Ligue A et
-- "Championship" Ligues B/C non importes : equipes qualifiees inconnues avant la fin des
-- groupes (meme principe que V16/V23/V107).
INSERT INTO competition (code, name, type, country, season) VALUES ('CONCACAF_NL_2627', 'Ligue des Nations Concacaf 2026-2027', 'INTERNATIONAL', NULL, 2027);

-- Equipes (nom = pays), garde-fou WHERE NOT EXISTS au cas improbable ou un club porterait deja ce nom.
INSERT INTO team (name, country) SELECT 'Costa Rica', 'Costa Rica' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Costa Rica');
INSERT INTO team (name, country) SELECT 'Haiti', 'Haiti' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Haiti');
INSERT INTO team (name, country) SELECT 'Trinite-et-Tobago', 'Trinite-et-Tobago' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Trinite-et-Tobago');
INSERT INTO team (name, country) SELECT 'Curacao', 'Curacao' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Curacao');
INSERT INTO team (name, country) SELECT 'Nicaragua', 'Nicaragua' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Nicaragua');
INSERT INTO team (name, country) SELECT 'Republique Dominicaine', 'Republique Dominicaine' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Republique Dominicaine');
INSERT INTO team (name, country) SELECT 'Honduras', 'Honduras' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Honduras');
INSERT INTO team (name, country) SELECT 'Jamaique', 'Jamaique' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Jamaique');
INSERT INTO team (name, country) SELECT 'Guatemala', 'Guatemala' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Guatemala');
INSERT INTO team (name, country) SELECT 'Suriname', 'Suriname' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Suriname');
INSERT INTO team (name, country) SELECT 'Martinique', 'Martinique' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Martinique');
INSERT INTO team (name, country) SELECT 'Salvador', 'Salvador' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Salvador');
INSERT INTO team (name, country) SELECT 'Porto Rico', 'Porto Rico' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Porto Rico');
INSERT INTO team (name, country) SELECT 'Guyana', 'Guyana' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Guyana');
INSERT INTO team (name, country) SELECT 'Iles Caimans', 'Iles Caimans' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Iles Caimans');
INSERT INTO team (name, country) SELECT 'Dominique', 'Dominique' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Dominique');
INSERT INTO team (name, country) SELECT 'Bermudes', 'Bermudes' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Bermudes');
INSERT INTO team (name, country) SELECT 'Guadeloupe', 'Guadeloupe' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Guadeloupe');
INSERT INTO team (name, country) SELECT 'Barbade', 'Barbade' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Barbade');
INSERT INTO team (name, country) SELECT 'Sainte-Lucie', 'Sainte-Lucie' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Sainte-Lucie');
INSERT INTO team (name, country) SELECT 'Grenade', 'Grenade' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Grenade');
INSERT INTO team (name, country) SELECT 'Cuba', 'Cuba' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Cuba');
INSERT INTO team (name, country) SELECT 'Bonaire', 'Bonaire' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Bonaire');
INSERT INTO team (name, country) SELECT 'Saint-Kitts-et-Nevis', 'Saint-Kitts-et-Nevis' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Saint-Kitts-et-Nevis');
INSERT INTO team (name, country) SELECT 'Saint-Vincent-et-les-Grenadines', 'Saint-Vincent-et-les-Grenadines' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines');
INSERT INTO team (name, country) SELECT 'Guyane', 'Guyane' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Guyane');
INSERT INTO team (name, country) SELECT 'Sint Maarten', 'Sint Maarten' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Sint Maarten');
INSERT INTO team (name, country) SELECT 'Belize', 'Belize' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Belize');
INSERT INTO team (name, country) SELECT 'Turks-et-Caicos', 'Turks-et-Caicos' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Turks-et-Caicos');
INSERT INTO team (name, country) SELECT 'Montserrat', 'Montserrat' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Montserrat');
INSERT INTO team (name, country) SELECT 'Iles Vierges Britanniques', 'Iles Vierges Britanniques' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Iles Vierges Britanniques');
INSERT INTO team (name, country) SELECT 'Antigua-et-Barbuda', 'Antigua-et-Barbuda' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Antigua-et-Barbuda');
INSERT INTO team (name, country) SELECT 'Aruba', 'Aruba' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Aruba');
INSERT INTO team (name, country) SELECT 'Anguilla', 'Anguilla' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Anguilla');
INSERT INTO team (name, country) SELECT 'Saint-Martin', 'Saint-Martin' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Saint-Martin');
INSERT INTO team (name, country) SELECT 'Bahamas', 'Bahamas' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Bahamas');
INSERT INTO team (name, country) SELECT 'Iles Vierges des Etats-Unis', 'Iles Vierges des Etats-Unis' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Iles Vierges des Etats-Unis');

-- Groupes
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Costa Rica'), 'Ligue A - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Haiti'), 'Ligue A - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Trinite-et-Tobago'), 'Ligue A - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Curacao'), 'Ligue A - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Nicaragua'), 'Ligue A - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Republique Dominicaine'), 'Ligue A - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Honduras'), 'Ligue A - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Jamaique'), 'Ligue A - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Guatemala'), 'Ligue A - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Suriname'), 'Ligue A - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Martinique'), 'Ligue A - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Salvador'), 'Ligue A - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Guyana'), 'Ligue B - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Porto Rico'), 'Ligue B - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Dominique'), 'Ligue B - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Iles Caimans'), 'Ligue B - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Guadeloupe'), 'Ligue B - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Bermudes'), 'Ligue B - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Sainte-Lucie'), 'Ligue B - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Barbade'), 'Ligue B - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Cuba'), 'Ligue B - Groupe 3');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Grenade'), 'Ligue B - Groupe 3');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), 'Ligue B - Groupe 3');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Bonaire'), 'Ligue B - Groupe 3');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Guyane'), 'Ligue B - Groupe 4');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), 'Ligue B - Groupe 4');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Belize'), 'Ligue B - Groupe 4');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Sint Maarten'), 'Ligue B - Groupe 4');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Turks-et-Caicos'), 'Ligue C - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Montserrat'), 'Ligue C - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Iles Vierges Britanniques'), 'Ligue C - Groupe 1');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Antigua-et-Barbuda'), 'Ligue C - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Aruba'), 'Ligue C - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Anguilla'), 'Ligue C - Groupe 2');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Saint-Martin'), 'Ligue C - Groupe 3');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Bahamas'), 'Ligue C - Groupe 3');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), (SELECT id FROM team WHERE name = 'Iles Vierges des Etats-Unis'), 'Ligue C - Groupe 3');

-- Ligue A - Groupe 1 (Costa Rica, Haiti, Trinite-et-Tobago, Curacao, Nicaragua, Republique Dominicaine)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-24', '20:00:00', (SELECT id FROM team WHERE name = 'Republique Dominicaine'), (SELECT id FROM team WHERE name = 'Nicaragua'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-24', '20:00:00', (SELECT id FROM team WHERE name = 'Haiti'), (SELECT id FROM team WHERE name = 'Trinite-et-Tobago'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-24', '22:00:00', (SELECT id FROM team WHERE name = 'Costa Rica'), (SELECT id FROM team WHERE name = 'Curacao'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-27', '19:00:00', (SELECT id FROM team WHERE name = 'Haiti'), (SELECT id FROM team WHERE name = 'Costa Rica'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-27', '20:00:00', (SELECT id FROM team WHERE name = 'Curacao'), (SELECT id FROM team WHERE name = 'Nicaragua'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-27', '21:00:00', (SELECT id FROM team WHERE name = 'Trinite-et-Tobago'), (SELECT id FROM team WHERE name = 'Republique Dominicaine'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-01', '18:00:00', (SELECT id FROM team WHERE name = 'Curacao'), (SELECT id FROM team WHERE name = 'Trinite-et-Tobago'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-01', '20:00:00', (SELECT id FROM team WHERE name = 'Republique Dominicaine'), (SELECT id FROM team WHERE name = 'Haiti'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-01', '22:00:00', (SELECT id FROM team WHERE name = 'Nicaragua'), (SELECT id FROM team WHERE name = 'Costa Rica'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-04', '18:00:00', (SELECT id FROM team WHERE name = 'Trinite-et-Tobago'), (SELECT id FROM team WHERE name = 'Curacao'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-04', '20:00:00', (SELECT id FROM team WHERE name = 'Costa Rica'), (SELECT id FROM team WHERE name = 'Haiti'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-04', '22:00:00', (SELECT id FROM team WHERE name = 'Nicaragua'), (SELECT id FROM team WHERE name = 'Republique Dominicaine'), NULL, NULL, 'SCHEDULED');

-- Ligue A - Groupe 2 (Honduras, Jamaique, Guatemala, Suriname, Martinique, Salvador)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '20:00:00', (SELECT id FROM team WHERE name = 'Jamaique'), (SELECT id FROM team WHERE name = 'Guatemala'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '21:00:00', (SELECT id FROM team WHERE name = 'Honduras'), (SELECT id FROM team WHERE name = 'Suriname'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '23:00:00', (SELECT id FROM team WHERE name = 'Salvador'), (SELECT id FROM team WHERE name = 'Martinique'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '18:00:00', (SELECT id FROM team WHERE name = 'Suriname'), (SELECT id FROM team WHERE name = 'Martinique'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '20:00:00', (SELECT id FROM team WHERE name = 'Jamaique'), (SELECT id FROM team WHERE name = 'Honduras'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '22:00:00', (SELECT id FROM team WHERE name = 'Guatemala'), (SELECT id FROM team WHERE name = 'Salvador'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '18:00:00', (SELECT id FROM team WHERE name = 'Suriname'), (SELECT id FROM team WHERE name = 'Guatemala'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '20:00:00', (SELECT id FROM team WHERE name = 'Martinique'), (SELECT id FROM team WHERE name = 'Honduras'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '22:00:00', (SELECT id FROM team WHERE name = 'Salvador'), (SELECT id FROM team WHERE name = 'Jamaique'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '18:00:00', (SELECT id FROM team WHERE name = 'Martinique'), (SELECT id FROM team WHERE name = 'Salvador'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '20:00:00', (SELECT id FROM team WHERE name = 'Guatemala'), (SELECT id FROM team WHERE name = 'Suriname'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '22:00:00', (SELECT id FROM team WHERE name = 'Honduras'), (SELECT id FROM team WHERE name = 'Jamaique'), NULL, NULL, 'SCHEDULED');

-- Ligue B - Groupe 1 (Guyana, Porto Rico, Dominique, Iles Caimans)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-24', '15:00:00', (SELECT id FROM team WHERE name = 'Porto Rico'), (SELECT id FROM team WHERE name = 'Guyana'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-24', '20:00:00', (SELECT id FROM team WHERE name = 'Iles Caimans'), (SELECT id FROM team WHERE name = 'Dominique'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-27', '15:00:00', (SELECT id FROM team WHERE name = 'Guyana'), (SELECT id FROM team WHERE name = 'Iles Caimans'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-27', '20:00:00', (SELECT id FROM team WHERE name = 'Dominique'), (SELECT id FROM team WHERE name = 'Porto Rico'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-01', '17:00:00', (SELECT id FROM team WHERE name = 'Dominique'), (SELECT id FROM team WHERE name = 'Guyana'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-01', '20:00:00', (SELECT id FROM team WHERE name = 'Iles Caimans'), (SELECT id FROM team WHERE name = 'Porto Rico'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-04', '15:00:00', (SELECT id FROM team WHERE name = 'Guyana'), (SELECT id FROM team WHERE name = 'Dominique'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-04', '18:00:00', (SELECT id FROM team WHERE name = 'Porto Rico'), (SELECT id FROM team WHERE name = 'Iles Caimans'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Porto Rico'), (SELECT id FROM team WHERE name = 'Dominique'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Iles Caimans'), (SELECT id FROM team WHERE name = 'Guyana'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Guyana'), (SELECT id FROM team WHERE name = 'Porto Rico'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Dominique'), (SELECT id FROM team WHERE name = 'Iles Caimans'), NULL, NULL, 'SCHEDULED');

-- Ligue B - Groupe 2 (Guadeloupe, Bermudes, Sainte-Lucie, Barbade)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '15:00:00', (SELECT id FROM team WHERE name = 'Bermudes'), (SELECT id FROM team WHERE name = 'Guadeloupe'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '20:00:00', (SELECT id FROM team WHERE name = 'Barbade'), (SELECT id FROM team WHERE name = 'Sainte-Lucie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '15:00:00', (SELECT id FROM team WHERE name = 'Guadeloupe'), (SELECT id FROM team WHERE name = 'Barbade'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '20:00:00', (SELECT id FROM team WHERE name = 'Sainte-Lucie'), (SELECT id FROM team WHERE name = 'Bermudes'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '15:00:00', (SELECT id FROM team WHERE name = 'Sainte-Lucie'), (SELECT id FROM team WHERE name = 'Guadeloupe'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '20:00:00', (SELECT id FROM team WHERE name = 'Barbade'), (SELECT id FROM team WHERE name = 'Bermudes'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '15:00:00', (SELECT id FROM team WHERE name = 'Guadeloupe'), (SELECT id FROM team WHERE name = 'Sainte-Lucie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '20:00:00', (SELECT id FROM team WHERE name = 'Bermudes'), (SELECT id FROM team WHERE name = 'Barbade'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Bermudes'), (SELECT id FROM team WHERE name = 'Sainte-Lucie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Barbade'), (SELECT id FROM team WHERE name = 'Guadeloupe'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Guadeloupe'), (SELECT id FROM team WHERE name = 'Bermudes'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Sainte-Lucie'), (SELECT id FROM team WHERE name = 'Barbade'), NULL, NULL, 'SCHEDULED');

-- Ligue B - Groupe 3 (Cuba, Grenade, Saint-Kitts-et-Nevis, Bonaire)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '17:00:00', (SELECT id FROM team WHERE name = 'Grenade'), (SELECT id FROM team WHERE name = 'Cuba'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-25', '20:00:00', (SELECT id FROM team WHERE name = 'Bonaire'), (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '17:00:00', (SELECT id FROM team WHERE name = 'Cuba'), (SELECT id FROM team WHERE name = 'Bonaire'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-28', '20:00:00', (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), (SELECT id FROM team WHERE name = 'Grenade'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '17:00:00', (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), (SELECT id FROM team WHERE name = 'Cuba'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-02', '20:00:00', (SELECT id FROM team WHERE name = 'Bonaire'), (SELECT id FROM team WHERE name = 'Grenade'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '17:00:00', (SELECT id FROM team WHERE name = 'Cuba'), (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-05', '20:00:00', (SELECT id FROM team WHERE name = 'Grenade'), (SELECT id FROM team WHERE name = 'Bonaire'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Grenade'), (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Bonaire'), (SELECT id FROM team WHERE name = 'Cuba'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Cuba'), (SELECT id FROM team WHERE name = 'Grenade'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Saint-Kitts-et-Nevis'), (SELECT id FROM team WHERE name = 'Bonaire'), NULL, NULL, 'SCHEDULED');

-- Ligue B - Groupe 4 (Guyane, Saint-Vincent-et-les-Grenadines, Belize, Sint Maarten)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-26', '17:00:00', (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), (SELECT id FROM team WHERE name = 'Guyane'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-26', '22:00:00', (SELECT id FROM team WHERE name = 'Sint Maarten'), (SELECT id FROM team WHERE name = 'Belize'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-29', '17:00:00', (SELECT id FROM team WHERE name = 'Guyane'), (SELECT id FROM team WHERE name = 'Sint Maarten'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-29', '22:00:00', (SELECT id FROM team WHERE name = 'Belize'), (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-03', '17:00:00', (SELECT id FROM team WHERE name = 'Sint Maarten'), (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-10-03', '22:00:00', (SELECT id FROM team WHERE name = 'Belize'), (SELECT id FROM team WHERE name = 'Guyane'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-06', '17:00:00', (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), (SELECT id FROM team WHERE name = 'Sint Maarten'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-06', '22:00:00', (SELECT id FROM team WHERE name = 'Guyane'), (SELECT id FROM team WHERE name = 'Belize'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), (SELECT id FROM team WHERE name = 'Belize'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', NULL, NULL, (SELECT id FROM team WHERE name = 'Sint Maarten'), (SELECT id FROM team WHERE name = 'Guyane'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Guyane'), (SELECT id FROM team WHERE name = 'Saint-Vincent-et-les-Grenadines'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', NULL, NULL, (SELECT id FROM team WHERE name = 'Belize'), (SELECT id FROM team WHERE name = 'Sint Maarten'), NULL, NULL, 'SCHEDULED');

-- Ligue C - Groupe 1, aller-retour (Turks-et-Caicos, Montserrat, Iles Vierges Britanniques)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-23', '15:00:00', (SELECT id FROM team WHERE name = 'Turks-et-Caicos'), (SELECT id FROM team WHERE name = 'Montserrat'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-26', '15:00:00', (SELECT id FROM team WHERE name = 'Montserrat'), (SELECT id FROM team WHERE name = 'Iles Vierges Britanniques'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-09-29', '15:00:00', (SELECT id FROM team WHERE name = 'Iles Vierges Britanniques'), (SELECT id FROM team WHERE name = 'Turks-et-Caicos'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-01', '15:00:00', (SELECT id FROM team WHERE name = 'Iles Vierges Britanniques'), (SELECT id FROM team WHERE name = 'Montserrat'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', '2026-10-04', '15:00:00', (SELECT id FROM team WHERE name = 'Turks-et-Caicos'), (SELECT id FROM team WHERE name = 'Iles Vierges Britanniques'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', '2026-10-06', '15:00:00', (SELECT id FROM team WHERE name = 'Montserrat'), (SELECT id FROM team WHERE name = 'Turks-et-Caicos'), NULL, NULL, 'SCHEDULED');

-- Ligue C - Groupe 2, aller-retour (Antigua-et-Barbuda, Aruba, Anguilla)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-23', '19:00:00', (SELECT id FROM team WHERE name = 'Aruba'), (SELECT id FROM team WHERE name = 'Antigua-et-Barbuda'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-26', '19:00:00', (SELECT id FROM team WHERE name = 'Antigua-et-Barbuda'), (SELECT id FROM team WHERE name = 'Anguilla'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-09-29', '19:00:00', (SELECT id FROM team WHERE name = 'Anguilla'), (SELECT id FROM team WHERE name = 'Aruba'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-01', '19:00:00', (SELECT id FROM team WHERE name = 'Anguilla'), (SELECT id FROM team WHERE name = 'Antigua-et-Barbuda'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', '2026-10-04', '19:00:00', (SELECT id FROM team WHERE name = 'Aruba'), (SELECT id FROM team WHERE name = 'Anguilla'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', '2026-10-06', '19:00:00', (SELECT id FROM team WHERE name = 'Antigua-et-Barbuda'), (SELECT id FROM team WHERE name = 'Aruba'), NULL, NULL, 'SCHEDULED');

-- Ligue C - Groupe 3, aller-retour (Saint-Martin, Bahamas, Iles Vierges des Etats-Unis)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J1', '2026-09-23', '16:00:00', (SELECT id FROM team WHERE name = 'Bahamas'), (SELECT id FROM team WHERE name = 'Saint-Martin'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J2', '2026-09-26', '16:00:00', (SELECT id FROM team WHERE name = 'Saint-Martin'), (SELECT id FROM team WHERE name = 'Iles Vierges des Etats-Unis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J3', '2026-09-29', '16:00:00', (SELECT id FROM team WHERE name = 'Iles Vierges des Etats-Unis'), (SELECT id FROM team WHERE name = 'Bahamas'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J4', '2026-10-01', '16:00:00', (SELECT id FROM team WHERE name = 'Iles Vierges des Etats-Unis'), (SELECT id FROM team WHERE name = 'Saint-Martin'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J5', '2026-10-04', '16:00:00', (SELECT id FROM team WHERE name = 'Bahamas'), (SELECT id FROM team WHERE name = 'Iles Vierges des Etats-Unis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'CONCACAF_NL_2627' AND season = 2027), 'J6', '2026-10-06', '16:00:00', (SELECT id FROM team WHERE name = 'Saint-Martin'), (SELECT id FROM team WHERE name = 'Bahamas'), NULL, NULL, 'SCHEDULED');
