-- Coupe d'Asie des nations 2027 (Arabie Saoudite, 7 janvier-5 fevrier 2027) : phase de groupes
-- uniquement (6 groupes de 4, tirage au sort effectue le 9 mai 2026), sources Wikipedia
-- (page principale + tableau des matchs par groupe, recoupees entre elles) :
--   https://en.wikipedia.org/wiki/2027_AFC_Asian_Cup
-- Horaires locaux (Arabie Saoudite, UTC+3) tels que publies au calendrier. Huitiemes de finale
-- et tours suivants non importes : equipes qualifiees inconnues avant la fin des groupes (meme
-- principe que V16/V23/V107/V108).
INSERT INTO competition (code, name, type, country, season) VALUES ('AFC_ASIANCUP_2027', 'Coupe d''Asie 2027', 'INTERNATIONAL', NULL, 2027);

-- Equipes (nom = pays), garde-fou WHERE NOT EXISTS au cas improbable ou un club porterait deja ce nom.
INSERT INTO team (name, country) SELECT 'Arabie Saoudite', 'Arabie Saoudite' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Arabie Saoudite');
INSERT INTO team (name, country) SELECT 'Koweit', 'Koweit' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Koweit');
INSERT INTO team (name, country) SELECT 'Oman', 'Oman' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Oman');
INSERT INTO team (name, country) SELECT 'Palestine', 'Palestine' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Palestine');
INSERT INTO team (name, country) SELECT 'Ouzbekistan', 'Ouzbekistan' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Ouzbekistan');
INSERT INTO team (name, country) SELECT 'Bahrein', 'Bahrein' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Bahrein');
INSERT INTO team (name, country) SELECT 'Coree du Nord', 'Coree du Nord' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Coree du Nord');
INSERT INTO team (name, country) SELECT 'Jordanie', 'Jordanie' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Jordanie');
INSERT INTO team (name, country) SELECT 'Iran', 'Iran' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Iran');
INSERT INTO team (name, country) SELECT 'Syrie', 'Syrie' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Syrie');
INSERT INTO team (name, country) SELECT 'Kirghizstan', 'Kirghizstan' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Kirghizstan');
INSERT INTO team (name, country) SELECT 'Chine', 'Chine' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Chine');
INSERT INTO team (name, country) SELECT 'Australie', 'Australie' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Australie');
INSERT INTO team (name, country) SELECT 'Tadjikistan', 'Tadjikistan' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Tadjikistan');
INSERT INTO team (name, country) SELECT 'Irak', 'Irak' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Irak');
INSERT INTO team (name, country) SELECT 'Singapour', 'Singapour' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Singapour');
INSERT INTO team (name, country) SELECT 'Coree du Sud', 'Coree du Sud' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Coree du Sud');
INSERT INTO team (name, country) SELECT 'Emirats Arabes Unis', 'Emirats Arabes Unis' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Emirats Arabes Unis');
INSERT INTO team (name, country) SELECT 'Vietnam', 'Vietnam' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Vietnam');
INSERT INTO team (name, country) SELECT 'Yemen', 'Yemen' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Yemen');
INSERT INTO team (name, country) SELECT 'Japon', 'Japon' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Japon');
INSERT INTO team (name, country) SELECT 'Qatar', 'Qatar' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Qatar');
INSERT INTO team (name, country) SELECT 'Thailande', 'Thailande' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Thailande');
INSERT INTO team (name, country) SELECT 'Indonesie', 'Indonesie' WHERE NOT EXISTS (SELECT 1 FROM team WHERE name = 'Indonesie');

-- Groupes
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Arabie Saoudite'), 'Groupe A');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Koweit'), 'Groupe A');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Oman'), 'Groupe A');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Palestine'), 'Groupe A');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Ouzbekistan'), 'Groupe B');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Bahrein'), 'Groupe B');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Coree du Nord'), 'Groupe B');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Jordanie'), 'Groupe B');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Iran'), 'Groupe C');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Syrie'), 'Groupe C');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Kirghizstan'), 'Groupe C');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Chine'), 'Groupe C');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Australie'), 'Groupe D');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Tadjikistan'), 'Groupe D');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Irak'), 'Groupe D');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Singapour'), 'Groupe D');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Coree du Sud'), 'Groupe E');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Emirats Arabes Unis'), 'Groupe E');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Vietnam'), 'Groupe E');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Yemen'), 'Groupe E');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Japon'), 'Groupe F');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Qatar'), 'Groupe F');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Thailande'), 'Groupe F');
INSERT INTO team_competition_status (competition_id, team_id, group_name) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), (SELECT id FROM team WHERE name = 'Indonesie'), 'Groupe F');

-- Groupe A (Arabie Saoudite, Koweit, Oman, Palestine)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-07', '20:00:00', (SELECT id FROM team WHERE name = 'Arabie Saoudite'), (SELECT id FROM team WHERE name = 'Palestine'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-08', '17:00:00', (SELECT id FROM team WHERE name = 'Oman'), (SELECT id FROM team WHERE name = 'Koweit'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-12', '17:00:00', (SELECT id FROM team WHERE name = 'Oman'), (SELECT id FROM team WHERE name = 'Arabie Saoudite'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-12', '20:00:00', (SELECT id FROM team WHERE name = 'Palestine'), (SELECT id FROM team WHERE name = 'Koweit'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-17', '17:00:00', (SELECT id FROM team WHERE name = 'Oman'), (SELECT id FROM team WHERE name = 'Palestine'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-17', '20:00:00', (SELECT id FROM team WHERE name = 'Arabie Saoudite'), (SELECT id FROM team WHERE name = 'Koweit'), NULL, NULL, 'SCHEDULED');

-- Groupe B (Ouzbekistan, Bahrein, Coree du Nord, Jordanie)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-08', '20:00:00', (SELECT id FROM team WHERE name = 'Bahrein'), (SELECT id FROM team WHERE name = 'Coree du Nord'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-08', '20:00:00', (SELECT id FROM team WHERE name = 'Ouzbekistan'), (SELECT id FROM team WHERE name = 'Jordanie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-13', '17:00:00', (SELECT id FROM team WHERE name = 'Coree du Nord'), (SELECT id FROM team WHERE name = 'Ouzbekistan'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-13', '20:00:00', (SELECT id FROM team WHERE name = 'Jordanie'), (SELECT id FROM team WHERE name = 'Bahrein'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-18', '17:00:00', (SELECT id FROM team WHERE name = 'Coree du Nord'), (SELECT id FROM team WHERE name = 'Jordanie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-18', '20:00:00', (SELECT id FROM team WHERE name = 'Ouzbekistan'), (SELECT id FROM team WHERE name = 'Bahrein'), NULL, NULL, 'SCHEDULED');

-- Groupe C (Iran, Syrie, Kirghizstan, Chine)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-09', '17:00:00', (SELECT id FROM team WHERE name = 'Syrie'), (SELECT id FROM team WHERE name = 'Kirghizstan'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-09', '20:00:00', (SELECT id FROM team WHERE name = 'Iran'), (SELECT id FROM team WHERE name = 'Chine'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-13', '20:00:00', (SELECT id FROM team WHERE name = 'Kirghizstan'), (SELECT id FROM team WHERE name = 'Iran'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-14', '17:00:00', (SELECT id FROM team WHERE name = 'Chine'), (SELECT id FROM team WHERE name = 'Syrie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-18', '20:00:00', (SELECT id FROM team WHERE name = 'Iran'), (SELECT id FROM team WHERE name = 'Syrie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-18', '20:00:00', (SELECT id FROM team WHERE name = 'Kirghizstan'), (SELECT id FROM team WHERE name = 'Chine'), NULL, NULL, 'SCHEDULED');

-- Groupe D (Australie, Tadjikistan, Irak, Singapour)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-09', '20:00:00', (SELECT id FROM team WHERE name = 'Australie'), (SELECT id FROM team WHERE name = 'Singapour'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-10', '17:00:00', (SELECT id FROM team WHERE name = 'Tadjikistan'), (SELECT id FROM team WHERE name = 'Irak'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-14', '17:00:00', (SELECT id FROM team WHERE name = 'Irak'), (SELECT id FROM team WHERE name = 'Australie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-14', '20:00:00', (SELECT id FROM team WHERE name = 'Singapour'), (SELECT id FROM team WHERE name = 'Tadjikistan'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-19', '17:00:00', (SELECT id FROM team WHERE name = 'Australie'), (SELECT id FROM team WHERE name = 'Tadjikistan'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-19', '20:00:00', (SELECT id FROM team WHERE name = 'Irak'), (SELECT id FROM team WHERE name = 'Singapour'), NULL, NULL, 'SCHEDULED');

-- Groupe E (Coree du Sud, Emirats Arabes Unis, Vietnam, Yemen)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-10', '20:00:00', (SELECT id FROM team WHERE name = 'Coree du Sud'), (SELECT id FROM team WHERE name = 'Yemen'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-10', '20:00:00', (SELECT id FROM team WHERE name = 'Emirats Arabes Unis'), (SELECT id FROM team WHERE name = 'Vietnam'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-15', '17:00:00', (SELECT id FROM team WHERE name = 'Yemen'), (SELECT id FROM team WHERE name = 'Emirats Arabes Unis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-15', '20:00:00', (SELECT id FROM team WHERE name = 'Vietnam'), (SELECT id FROM team WHERE name = 'Coree du Sud'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-20', '17:00:00', (SELECT id FROM team WHERE name = 'Coree du Sud'), (SELECT id FROM team WHERE name = 'Emirats Arabes Unis'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-20', '20:00:00', (SELECT id FROM team WHERE name = 'Vietnam'), (SELECT id FROM team WHERE name = 'Yemen'), NULL, NULL, 'SCHEDULED');

-- Groupe F (Japon, Qatar, Thailande, Indonesie)
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-11', '17:00:00', (SELECT id FROM team WHERE name = 'Qatar'), (SELECT id FROM team WHERE name = 'Thailande'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J1', '2027-01-11', '20:00:00', (SELECT id FROM team WHERE name = 'Japon'), (SELECT id FROM team WHERE name = 'Indonesie'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-16', '17:00:00', (SELECT id FROM team WHERE name = 'Thailande'), (SELECT id FROM team WHERE name = 'Japon'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J2', '2027-01-16', '20:00:00', (SELECT id FROM team WHERE name = 'Indonesie'), (SELECT id FROM team WHERE name = 'Qatar'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-20', '17:00:00', (SELECT id FROM team WHERE name = 'Japon'), (SELECT id FROM team WHERE name = 'Qatar'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'AFC_ASIANCUP_2027' AND season = 2027), 'J3', '2027-01-20', '20:00:00', (SELECT id FROM team WHERE name = 'Thailande'), (SELECT id FROM team WHERE name = 'Indonesie'), NULL, NULL, 'SCHEDULED');
