-- 18 matchs de la derniere journee (J8) de la phase de ligue LDC manquants de
-- V6 : la feuille Excel note ces dates au format court "J/M" (ex: "27/1")
-- plutot qu'une vraie date, ce qui les rendait invisibles a une simple lecture
-- de cellule. Toutes tombent le 27 janvier 2027 (cf. V8 : la saison se termine
-- en janvier de la 2e annee civile). Voir import/extract_league_phase.py.
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'PSG'), (SELECT id FROM team WHERE name = 'GALATASARAY'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'BAYERN MUNICH'), (SELECT id FROM team WHERE name = 'BETIS'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'LIVERPOOL'), (SELECT id FROM team WHERE name = 'LENS'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'MANCHESTER CITY'), (SELECT id FROM team WHERE name = 'SPORTING'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'ARSENAL'), (SELECT id FROM team WHERE name = 'SABAH FC'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'BARCELONE'), (SELECT id FROM team WHERE name = 'COMO'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'ATL. MADRID'), (SELECT id FROM team WHERE name = 'FENERBAHCE SK'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'DORTMUND'), (SELECT id FROM team WHERE name = 'AEK ATHENES'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'AS ROME'), (SELECT id FROM team WHERE name = 'LILLE'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'CLUB BRUGGE'), (SELECT id FROM team WHERE name = 'FK BODO GLIMT'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'PSV'), (SELECT id FROM team WHERE name = 'STUTTGART'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'FEYENOORD'), (SELECT id FROM team WHERE name = 'RB LEIPZIG'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'NAPLES'), (SELECT id FROM team WHERE name = 'VIKING FK'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'VILLAREAL'), (SELECT id FROM team WHERE name = 'MANCHESTER UTD'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'CHAKTHAR DONETSK'), (SELECT id FROM team WHERE name = 'REAL MADRID'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'SLAVIA PRAGUE'), (SELECT id FROM team WHERE name = 'ASTON VILLA'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'SLOVAN BRATISLAVA'), (SELECT id FROM team WHERE name = 'INTER'), NULL, NULL, 'SCHEDULED');
INSERT INTO match (competition_id, round_label, date, time, team1_id, team2_id, score1, score2, status) VALUES ((SELECT id FROM competition WHERE code = 'LDC' AND season = 2027), 'PHASE DE LIGUE', '2027-01-27', NULL, (SELECT id FROM team WHERE name = 'LASK'), (SELECT id FROM team WHERE name = 'FC PORTO'), NULL, NULL, 'SCHEDULED');
