-- Meme bug que V18 (Kosovo) repere dans ~40 championnats supplementaires : des clubs
-- fusionnes avec leur doublon coupe d'Europe ont garde le code pays court utilise pour
-- les tableaux de qualification europeenne (ex: 'ALB', 'CRO', 'POL'...) au lieu du nom
-- complet du pays utilise par la competition championnat correspondante, ce qui les
-- rend invisibles dans le selecteur d'equipes de /api/teams?competitionId=<championnat>.

UPDATE team SET country = 'Malte' WHERE id = 832 AND country = 'MAL'; -- FLORIANA FC (MALTE)
UPDATE team SET country = 'Estonie' WHERE id = 833 AND country = 'EST'; -- FLORA TALLINN (ESTONIE)
UPDATE team SET country = 'Georgie' WHERE id = 834 AND country = 'GEO'; -- FC IBERIA 1999 (GEORGIE)
UPDATE team SET country = 'Gibraltar' WHERE id = 835 AND country = 'GIB'; -- LINCOLN RED IMPS (GIBRALTAR)
UPDATE team SET country = 'San Marin' WHERE id = 837 AND country = 'SM'; -- TRE FIORI FC (SAN MARIN)
UPDATE team SET country = 'Irlande Nord' WHERE id = 838 AND country = 'IRN'; -- LARNE FC (IRLANDE NORD)
UPDATE team SET country = 'Macedoine' WHERE id = 839 AND country = 'MAC'; -- FK VARDAR SKOPJE (MACEDOINE)
UPDATE team SET country = 'Roumanie' WHERE id = 841 AND country = 'ROU'; -- UNIVERSITATEA CRAIOVA (ROUMANIE)
UPDATE team SET country = 'Moldavie' WHERE id = 842 AND country = 'MOL'; -- CS PETROCUB HINCESTI (MOLDAVIE)
UPDATE team SET country = 'Bosnie' WHERE id = 844 AND country = 'BOS'; -- FK BORAC BANJA LUKA (BOSNIE)
UPDATE team SET country = 'Bulgarie' WHERE id = 845 AND country = 'BUL'; -- LEVSKI SOFIA (BULGARIE)
UPDATE team SET country = 'Hongrie' WHERE id = 846 AND country = 'HON'; -- GYORI ETO FC (HONGRIE)
UPDATE team SET country = 'Montenegro' WHERE id = 847 AND country = 'MON'; -- SUTJESKA NIKSIC (MONTENEGRO)
UPDATE team SET country = 'Iles Feroe' WHERE id = 848 AND country = 'FER'; -- KI KLAKSVIK (ILES FEROE)
UPDATE team SET country = 'Luxembourg' WHERE id = 849 AND country = 'LUX'; -- FC ATERT BISSEN (LUXEMBOURG)
UPDATE team SET country = 'Suede' WHERE id = 850 AND country = 'SWE'; -- MJALLBY AIF (SUEDE)
UPDATE team SET country = 'Danemark' WHERE id = 851 AND country = 'DAN'; -- AGF AARHUS (DANEMARK)
UPDATE team SET country = 'Pologne' WHERE id = 852 AND country = 'POL'; -- LECH POZNAN (POLOGNE)
UPDATE team SET country = 'Croatie' WHERE id = 855 AND country = 'CRO'; -- DINAMO ZAGREB (CROATIE)
UPDATE team SET country = 'Slovenie' WHERE id = 857 AND country = 'SVN'; -- NK CELJE (SLOVENIE)
UPDATE team SET country = 'Turquie' WHERE id = 858 AND country = 'TUR'; -- FENERBAHCE SK (TURQUIE)
UPDATE team SET country = 'Norvege' WHERE id = 862 AND country = 'NOR'; -- FK BODO GLIMT (NORVEGE)
UPDATE team SET country = 'Grece' WHERE id = 864 AND country = 'GRE'; -- AEK ATHENES (GRECE)
UPDATE team SET country = 'Ecosse' WHERE id = 865 AND country = 'ECO'; -- CELTIC GLASGOW (ECOSSE)
UPDATE team SET country = 'Norvege' WHERE id = 866 AND country = 'NOR'; -- VIKING FK (NORVEGE)
UPDATE team SET country = 'Roumanie' WHERE id = 868 AND country = 'ROU'; -- UNIVERSITATEA CLUJ (ROUMANIE)
UPDATE team SET country = 'Azerbaidjan' WHERE id = 869 AND country = 'AZE'; -- QARABAG FK (AZERBAIDJAN)
UPDATE team SET country = 'Slovaquie' WHERE id = 871 AND country = 'SVK'; -- MSK ZILINA (SLOVAQUIE)
UPDATE team SET country = 'Moldavie' WHERE id = 872 AND country = 'MOL'; -- SHERIFF TIRASPOL (MOLDAVIE)
UPDATE team SET country = 'Slovenie' WHERE id = 873 AND country = 'SVN'; -- NK ALUMINIJ (SLOVENIE)
UPDATE team SET country = 'Serbie' WHERE id = 874 AND country = 'SRB'; -- VOJVODINA NOVI SAD (SERBIE)
UPDATE team SET country = 'Hongrie' WHERE id = 875 AND country = 'HON'; -- FERENCVAROS TC (HONGRIE)
UPDATE team SET country = 'Suede' WHERE id = 876 AND country = 'SWE'; -- HAMMARBY IF (SUEDE)
UPDATE team SET country = 'Belgique' WHERE id = 877 AND country = 'BEL'; -- RSC ANDERLECHT (BELGIQUE)
UPDATE team SET country = 'Norvege' WHERE id = 878 AND country = 'NOR'; -- TROMSO IL (NORVEGE)
UPDATE team SET country = 'Pays-Bas' WHERE id = 879 AND country = 'HOL'; -- FC TWENTE (PAYS-BAS)
UPDATE team SET country = 'Turquie' WHERE id = 880 AND country = 'TUR'; -- BESIKTAS JK (TURQUIE)
UPDATE team SET country = 'Danemark' WHERE id = 881 AND country = 'DAN'; -- FC MIDTJYLLAND (DANEMARK)
UPDATE team SET country = 'Chypre' WHERE id = 882 AND country = 'CYP'; -- FC PAFOS (CHYPRE)
UPDATE team SET country = 'Portugal' WHERE id = 885 AND country = 'POR'; -- SL BENFICA (PORTUGAL)
UPDATE team SET country = 'Pologne' WHERE id = 887 AND country = 'POL'; -- JAGIELLONIA BIALYSTOK (POLOGNE)
UPDATE team SET country = 'Ecosse' WHERE id = 889 AND country = 'ECO'; -- HEARTS OF MIDDLOTHIAN (ECOSSE)
UPDATE team SET country = 'Tchequie' WHERE id = 891 AND country = 'CZE'; -- VIKTORIA PLZEN (TCHEQUIE)
UPDATE team SET country = 'Galles' WHERE id = 893 AND country = 'GAL'; -- CONNAH'S QUAY NOMADS (GALLES)
UPDATE team SET country = 'Gibraltar' WHERE id = 896 AND country = 'GIB'; -- ST JOSEPH'S FC (GIBRALTAR)
UPDATE team SET country = 'Albanie' WHERE id = 897 AND country = 'ALB'; -- DINAMO TIRANA (ALBANIE)
UPDATE team SET country = 'Bosnie' WHERE id = 899 AND country = 'BOS'; -- FK VELEZ MOSTAR (BOSNIE)
UPDATE team SET country = 'Moldavie' WHERE id = 900 AND country = 'MOL'; -- FC MILSAMI ORHEI (MOLDAVIE)
UPDATE team SET country = 'Belarus' WHERE id = 901 AND country = 'BLR'; -- DINAMO MINSK (BELARUS)
UPDATE team SET country = 'Macedoine' WHERE id = 902 AND country = 'MAC'; -- FK SILEKS KRATOVO (MACEDOINE)
UPDATE team SET country = 'Georgie' WHERE id = 904 AND country = 'GEO'; -- TORPEDO KOUTAISSI (GEORGIE)
UPDATE team SET country = 'Luxembourg' WHERE id = 905 AND country = 'LUX'; -- FC DIFFERDANGE 03 (LUXEMBOURG)
UPDATE team SET country = 'Finlande' WHERE id = 906 AND country = 'FIN'; -- FC ILVES (FINLANDE)
UPDATE team SET country = 'Montenegro' WHERE id = 907 AND country = 'MON'; -- DECIC TUZI (MONTENEGRO)
UPDATE team SET country = 'Luxembourg' WHERE id = 908 AND country = 'LUX'; -- MONDORF LES BAINS (LUXEMBOURG)
UPDATE team SET country = 'Georgie' WHERE id = 909 AND country = 'GEO'; -- DINAMO TBILISSI (GEORGIE)
UPDATE team SET country = 'Montenegro' WHERE id = 910 AND country = 'MON'; -- MORNAR BAR (MONTENEGRO)
UPDATE team SET country = 'Irlande Nord' WHERE id = 912 AND country = 'IRN'; -- GLENTORAN FC (IRLANDE NORD)
UPDATE team SET country = 'Malte' WHERE id = 916 AND country = 'MAL'; -- MARSAXLOKK FC (MALTE)
UPDATE team SET country = 'Armenie' WHERE id = 917 AND country = 'ARM'; -- FC PYUNIK (ARMENIE)
UPDATE team SET country = 'Galles' WHERE id = 918 AND country = 'GAL'; -- CAERNARFON TOWN (GALLES)
UPDATE team SET country = 'Estonie' WHERE id = 919 AND country = 'EST'; -- FC LEVADIA TALLINN (ESTONIE)
UPDATE team SET country = 'Lituanie' WHERE id = 920 AND country = 'LIT'; -- FC HEGELMANN (LITUANIE)
UPDATE team SET country = 'Estonie' WHERE id = 921 AND country = 'EST'; -- PAIDE LINNAMEESKOND (ESTONIE)
UPDATE team SET country = 'Armenie' WHERE id = 922 AND country = 'ARM'; -- FC ALASHKERT (ARMENIE)
UPDATE team SET country = 'San Marin' WHERE id = 925 AND country = 'SM'; -- AC VIRTUS (SAN MARIN)
UPDATE team SET country = 'Bosnie' WHERE id = 926 AND country = 'BOS'; -- FK SARAJEVO (BOSNIE)
UPDATE team SET country = 'Macedoine' WHERE id = 927 AND country = 'MAC'; -- FK SHKENDIJA (MACEDOINE)
UPDATE team SET country = 'Estonie' WHERE id = 928 AND country = 'EST'; -- NOMME KALJU (ESTONIE)
UPDATE team SET country = 'Irlande Nord' WHERE id = 929 AND country = 'IRN'; -- LINFIELD FC (IRLANDE NORD)
UPDATE team SET country = 'Iles Feroe' WHERE id = 932 AND country = 'FER'; -- NSI RUNAVIK (ILES FEROE)
UPDATE team SET country = 'Malte' WHERE id = 933 AND country = 'MAL'; -- HAMRUN SPARTANS (MALTE)
UPDATE team SET country = 'San Marin' WHERE id = 935 AND country = 'SM'; -- SP LA FIORITA (SAN MARIN)
UPDATE team SET country = 'Albanie' WHERE id = 936 AND country = 'ALB'; -- FK VLLAZNIA SHKODER (ALBANIE)
UPDATE team SET country = 'Croatie' WHERE id = 938 AND country = 'CRO'; -- HNK RIJEKA (CROATIE)
UPDATE team SET country = 'Turquie' WHERE id = 939 AND country = 'TUR'; -- ISTANBUL BASAKSEHIR (TURQUIE)
UPDATE team SET country = 'Pologne' WHERE id = 944 AND country = 'POL'; -- RAKOW CZESTOCHOWA (POLOGNE)
UPDATE team SET country = 'Malte' WHERE id = 945 AND country = 'MAL'; -- VALLETTA FC (MALTE)
UPDATE team SET country = 'Hongrie' WHERE id = 946 AND country = 'HON'; -- DEBRECENI VSC (HONGRIE)
UPDATE team SET country = 'Suede' WHERE id = 948 AND country = 'SWE'; -- IFK GOTEBORG (SUEDE)
UPDATE team SET country = 'Pologne' WHERE id = 949 AND country = 'POL'; -- GKS KATOWICE (POLOGNE)
UPDATE team SET country = 'Croatie' WHERE id = 950 AND country = 'CRO'; -- NK VARAZDIN (CROATIE)
UPDATE team SET country = 'Chypre' WHERE id = 951 AND country = 'CYP'; -- APOLLON LIMASSOL (CHYPRE)
UPDATE team SET country = 'Slovenie' WHERE id = 952 AND country = 'SVN'; -- NK BRAVO (SLOVENIE)
UPDATE team SET country = 'Norvege' WHERE id = 953 AND country = 'NOR'; -- SK BRANN (NORVEGE)
UPDATE team SET country = 'Islande' WHERE id = 955 AND country = 'ISL'; -- VALUR REYKJAVIK (ISLANDE)
UPDATE team SET country = 'Bosnie' WHERE id = 956 AND country = 'BOS'; -- HSK ZRINJSKI MOSTAR (BOSNIE)
UPDATE team SET country = 'Moldavie' WHERE id = 957 AND country = 'MOL'; -- ZIMBRU CHISINAU (MOLDAVIE)
UPDATE team SET country = 'Ecosse' WHERE id = 961 AND country = 'ECO'; -- MOTHERWELL FC (ECOSSE)
UPDATE team SET country = 'Kazakhstan' WHERE id = 962 AND country = 'KAZ'; -- TOBOL KOSTANAI (KAZAKHSTAN)
UPDATE team SET country = 'Ecosse' WHERE id = 963 AND country = 'ECO'; -- HIBERNIAN FC (ECOSSE)
UPDATE team SET country = 'Portugal' WHERE id = 966 AND country = 'POR'; -- SPORTING BRAGA (PORTUGAL)
UPDATE team SET country = 'Belgique' WHERE id = 970 AND country = 'BEL'; -- KAA LA GANTOISE (BELGIQUE)
UPDATE team SET country = 'Bulgarie' WHERE id = 973 AND country = 'BUL'; -- LUDOGORETS RAZGRAD (BULGARIE)
UPDATE team SET country = 'Slovaquie' WHERE id = 974 AND country = 'SVK'; -- SPARTAK TRNAVA (SLOVAQUIE)
UPDATE team SET country = 'Slovenie' WHERE id = 975 AND country = 'SVN'; -- FC KOPER (SLOVENIE)
UPDATE team SET country = 'Allemagne' WHERE id = 979 AND country = 'ALL'; -- SC FRIBOURG (ALLEMAGNE)
UPDATE team SET country = 'France' WHERE id = 980 AND country = 'FRA'; -- AS MONACO (FRANCE)
UPDATE team SET country = 'Angleterre' WHERE id = 981 AND country = 'ANG'; -- BRIGHTON &HOVE ALBION (ANGLETERRE)
UPDATE team SET country = 'Italie' WHERE id = 982 AND country = 'ITA'; -- ATALANTA BERGAME (ITALIE)
