// Mappe le libellé pays (texte libre, tel qu'importé de l'Excel) vers un code
// ISO 3166-1 (ou sous-division) utilisé par le package flag-icons.
const COUNTRY_TO_FLAG = {
  Albanie: 'al',
  Allemagne: 'de',
  Andorre: 'ad',
  Angleterre: 'gb-eng',
  Armenie: 'am',
  Autriche: 'at',
  Azerbaidjan: 'az',
  Belarus: 'by',
  Belgique: 'be',
  Bosnie: 'ba',
  Bulgarie: 'bg',
  Chypre: 'cy',
  Croatie: 'hr',
  Danemark: 'dk',
  Ecosse: 'gb-sct',
  Eire: 'ie',
  Espagne: 'es',
  Estonie: 'ee',
  Finlande: 'fi',
  France: 'fr',
  Galles: 'gb-wls',
  Georgie: 'ge',
  Gibraltar: 'gi',
  Grece: 'gr',
  Hongrie: 'hu',
  'Iles Feroe': 'fo',
  'Irlande Nord': 'gb-nir',
  Islande: 'is',
  Israel: 'il',
  Italie: 'it',
  Kazakhstan: 'kz',
  Kosovo: 'xk',
  Lettonie: 'lv',
  Lituanie: 'lt',
  Luxembourg: 'lu',
  Macedoine: 'mk',
  Malte: 'mt',
  Moldavie: 'md',
  Montenegro: 'me',
  Norvege: 'no',
  'Pays-Bas': 'nl',
  Pologne: 'pl',
  Portugal: 'pt',
  Roumanie: 'ro',
  Russie: 'ru',
  'San Marin': 'sm',
  Serbie: 'rs',
  Slovaquie: 'sk',
  Slovenie: 'si',
  Suede: 'se',
  Suisse: 'ch',
  Tchequie: 'cz',
  Turquie: 'tr',
  Ukraine: 'ua'
}

// La table "equipe" utilise parfois le nom complet du pays, parfois un code
// court a 3 lettres, selon la feuille Excel d'origine (championnat vs coupes
// d'Europe) - voir la limitation documentee dans le README. On ramene les
// deux formes vers le meme libelle canonique pour que drapeau et couleur
// (voir teamColors.js) soient coherents.
const COUNTRY_ALIASES = {
  ALB: 'Albanie',
  ALL: 'Allemagne',
  AND: 'Andorre',
  ANG: 'Angleterre',
  ARM: 'Armenie',
  AUT: 'Autriche',
  AZE: 'Azerbaidjan',
  BEL: 'Belgique',
  BLR: 'Belarus',
  BOS: 'Bosnie',
  BUL: 'Bulgarie',
  CRO: 'Croatie',
  CYP: 'Chypre',
  CZE: 'Tchequie',
  DAN: 'Danemark',
  ECO: 'Ecosse',
  EST: 'Estonie',
  FER: 'Iles Feroe',
  FIN: 'Finlande',
  FRA: 'France',
  GAL: 'Galles',
  GEO: 'Georgie',
  GIB: 'Gibraltar',
  GRE: 'Grece',
  HOL: 'Pays-Bas',
  HON: 'Hongrie',
  IRN: 'Irlande Nord',
  ISL: 'Islande',
  ISR: 'Israel',
  ITA: 'Italie',
  KAZ: 'Kazakhstan',
  KOS: 'Kosovo',
  LET: 'Lettonie',
  LIT: 'Lituanie',
  LUX: 'Luxembourg',
  MAC: 'Macedoine',
  MAL: 'Malte',
  MOL: 'Moldavie',
  MON: 'Montenegro',
  NOR: 'Norvege',
  POL: 'Pologne',
  POR: 'Portugal',
  ROU: 'Roumanie',
  SM: 'San Marin',
  SRB: 'Serbie',
  SUI: 'Suisse',
  SVK: 'Slovaquie',
  SVN: 'Slovenie',
  SWE: 'Suede',
  TUR: 'Turquie',
  UKR: 'Ukraine'
}

export function canonicalCountry(country) {
  if (!country) return null
  return COUNTRY_ALIASES[country] ?? country
}

export function flagCode(country) {
  return COUNTRY_TO_FLAG[canonicalCountry(country)] ?? null
}
