// Mappe le libellé pays (texte libre, tel qu'importé de l'Excel) vers un code
// ISO 3166-1 (ou sous-division) utilisé par le package flag-icons.
const COUNTRY_TO_FLAG = {
  Albanie: 'al',
  Allemagne: 'de',
  Andorre: 'ad',
  Angleterre: 'gb-eng',
  Armenie: 'am',
  Autriche: 'at',
  Azerbaidjan: 'az',
  Belarus: 'by',
  Belgique: 'be',
  Bosnie: 'ba',
  Bulgarie: 'bg',
  Chypre: 'cy',
  Croatie: 'hr',
  Danemark: 'dk',
  Ecosse: 'gb-sct',
  Eire: 'ie',
  Espagne: 'es',
  Estonie: 'ee',
  Finlande: 'fi',
  France: 'fr',
  Galles: 'gb-wls',
  Georgie: 'ge',
  Gibraltar: 'gi',
  Grece: 'gr',
  Hongrie: 'hu',
  'Iles Feroe': 'fo',
  'Irlande Nord': 'gb-nir',
  Islande: 'is',
  Israel: 'il',
  Italie: 'it',
  Kazakhstan: 'kz',
  Kosovo: 'xk',
  Lettonie: 'lv',
  Lituanie: 'lt',
  Luxembourg: 'lu',
  Macedoine: 'mk',
  Malte: 'mt',
  Moldavie: 'md',
  Montenegro: 'me',
  Norvege: 'no',
  'Pays-Bas': 'nl',
  Pologne: 'pl',
  Portugal: 'pt',
  Roumanie: 'ro',
  Russie: 'ru',
  'San Marin': 'sm',
  Serbie: 'rs',
  Slovaquie: 'sk',
  Slovenie: 'si',
  Suede: 'se',
  Suisse: 'ch',
  Tchequie: 'cz',
  Turquie: 'tr',
  Ukraine: 'ua',
  Liechtenstein: 'li',
  // Confederation africaine (CAF) - qualifications CAN 2027, voir V107__caf_can_2027_qualifications.sql
  'Afrique du Sud': 'za',
  Algerie: 'dz',
  Angola: 'ao',
  Benin: 'bj',
  Botswana: 'bw',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  Cameroun: 'cm',
  'Cap-Vert': 'cv',
  Centrafrique: 'cf',
  Comores: 'km',
  Congo: 'cg',
  "Cote d'Ivoire": 'ci',
  Egypte: 'eg',
  Erythree: 'er',
  Ethiopie: 'et',
  Gabon: 'ga',
  Gambie: 'gm',
  Ghana: 'gh',
  Guinee: 'gn',
  'Guinee-Bissau': 'gw',
  'Guinee Equatoriale': 'gq',
  Kenya: 'ke',
  Lesotho: 'ls',
  Liberia: 'lr',
  Libye: 'ly',
  Madagascar: 'mg',
  Malawi: 'mw',
  Mali: 'ml',
  Maroc: 'ma',
  Mauritanie: 'mr',
  Mozambique: 'mz',
  Namibie: 'na',
  Niger: 'ne',
  Nigeria: 'ng',
  Ouganda: 'ug',
  'RD Congo': 'cd',
  Rwanda: 'rw',
  Senegal: 'sn',
  'Sierra Leone': 'sl',
  Somalie: 'so',
  Soudan: 'sd',
  'Soudan du Sud': 'ss',
  Tanzanie: 'tz',
  Togo: 'tg',
  Tunisie: 'tn',
  Zambie: 'zm',
  Zimbabwe: 'zw',
  // Concacaf - Ligue des Nations 2026-2027, voir V108__concacaf_ligue_des_nations_2026_2027.sql
  Anguilla: 'ai',
  'Antigua-et-Barbuda': 'ag',
  Aruba: 'aw',
  Bahamas: 'bs',
  Barbade: 'bb',
  Belize: 'bz',
  Bermudes: 'bm',
  Bonaire: 'bq',
  'Costa Rica': 'cr',
  Cuba: 'cu',
  Curacao: 'cw',
  Dominique: 'dm',
  Grenade: 'gd',
  Guadeloupe: 'gp',
  Guatemala: 'gt',
  Guyana: 'gy',
  Guyane: 'gf',
  Haiti: 'ht',
  Honduras: 'hn',
  'Iles Caimans': 'ky',
  'Iles Vierges Britanniques': 'vg',
  'Iles Vierges des Etats-Unis': 'vi',
  Jamaique: 'jm',
  Martinique: 'mq',
  Montserrat: 'ms',
  Nicaragua: 'ni',
  'Porto Rico': 'pr',
  'Republique Dominicaine': 'do',
  Salvador: 'sv',
  'Saint-Kitts-et-Nevis': 'kn',
  'Saint-Martin': 'mf',
  'Saint-Vincent-et-les-Grenadines': 'vc',
  'Sainte-Lucie': 'lc',
  'Sint Maarten': 'sx',
  Suriname: 'sr',
  'Trinite-et-Tobago': 'tt',
  'Turks-et-Caicos': 'tc',
  // AFC - Coupe d'Asie 2027, voir V109__afc_coupe_asie_2027.sql
  'Arabie Saoudite': 'sa',
  Australie: 'au',
  Bahrein: 'bh',
  Chine: 'cn',
  'Coree du Nord': 'kp',
  'Coree du Sud': 'kr',
  'Emirats Arabes Unis': 'ae',
  Indonesie: 'id',
  Irak: 'iq',
  Iran: 'ir',
  Japon: 'jp',
  Jordanie: 'jo',
  Kirghizstan: 'kg',
  Koweit: 'kw',
  Oman: 'om',
  Ouzbekistan: 'uz',
  Palestine: 'ps',
  Qatar: 'qa',
  Singapour: 'sg',
  Syrie: 'sy',
  Tadjikistan: 'tj',
  Thailande: 'th',
  Vietnam: 'vn',
  Yemen: 'ye'
}

// La table "equipe" utilise parfois le nom complet du pays, parfois un code
// court a 3 lettres, selon la feuille Excel d'origine (championnat vs coupes
// d'Europe) - voir la limitation documentee dans le README. On ramene les
// deux formes vers le meme libelle canonique pour que drapeau et couleur
// (voir teamColors.js) soient coherents.
const COUNTRY_ALIASES = {
  ALB: 'Albanie',
  ALL: 'Allemagne',
  AND: 'Andorre',
  ANG: 'Angleterre',
  ARM: 'Armenie',
  AUT: 'Autriche',
  AZE: 'Azerbaidjan',
  BEL: 'Belgique',
  BLR: 'Belarus',
  BOS: 'Bosnie',
  BUL: 'Bulgarie',
  CRO: 'Croatie',
  CYP: 'Chypre',
  CZE: 'Tchequie',
  DAN: 'Danemark',
  ECO: 'Ecosse',
  EST: 'Estonie',
  FER: 'Iles Feroe',
  FIN: 'Finlande',
  FRA: 'France',
  GAL: 'Galles',
  GEO: 'Georgie',
  GIB: 'Gibraltar',
  GRE: 'Grece',
  HOL: 'Pays-Bas',
  HON: 'Hongrie',
  IRN: 'Irlande Nord',
  ISL: 'Islande',
  ISR: 'Israel',
  ITA: 'Italie',
  KAZ: 'Kazakhstan',
  KOS: 'Kosovo',
  LET: 'Lettonie',
  LIT: 'Lituanie',
  LUX: 'Luxembourg',
  MAC: 'Macedoine',
  MAL: 'Malte',
  MOL: 'Moldavie',
  MON: 'Montenegro',
  NOR: 'Norvege',
  POL: 'Pologne',
  POR: 'Portugal',
  ROU: 'Roumanie',
  SM: 'San Marin',
  'Saint Marin': 'San Marin',
  'Iles Feroes': 'Iles Feroe',
  EIRE: 'Eire',
  SRB: 'Serbie',
  SUI: 'Suisse',
  SVK: 'Slovaquie',
  SVN: 'Slovenie',
  SWE: 'Suede',
  TUR: 'Turquie',
  UKR: 'Ukraine'
}

export function canonicalCountry(country) {
  if (!country) return null
  return COUNTRY_ALIASES[country] ?? country
}

export function flagCode(country) {
  return COUNTRY_TO_FLAG[canonicalCountry(country)] ?? null
}
